// <auto-generated />
namespace EmergencyInformationSystem.Models.Domains2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RoomAddField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoomAddField));
        
        string IMigrationMetadata.Id
        {
            get { return "201801291257327_RoomAddField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
