// <auto-generated />
namespace EmergencyInformationSystem.Models.Domains3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddAmi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAmi));
        
        string IMigrationMetadata.Id
        {
            get { return "201802011424318_AddAmi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
